# Generated by Django 5.1.15 on 2026-09-17 14:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique notification record identifier', primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('CONFIRMATION', 'Confirmation'), ('REMINDER', 'Reminder')], db_index=True, help_text='Type of message (confirmation or reminder)', max_length=20)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email')], db_index=True, help_text='Delivery communication channel', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('QUEUED', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Current state in the notification lifecycle', max_length=20)),
                ('scheduled_at', models.DateTimeField(db_index=True, help_text='Timestamp when this notification is eligible to be dispatched')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Timestamp when message was successfully delivered or acknowledged', null=True)),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Number of delivery attempts performed')),
                ('last_error', models.TextField(blank=True, help_text='Most recent error message if delivery or processing failed', null=True)),
                ('external_id', models.CharField(blank=True, help_text='External identifier from automation platform or provider (e.g. Evolution API message ID)', max_length=255, null=True)),
                ('processing_started_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when a worker claimed this notification for crash recovery lease timeout', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.ForeignKey(help_text='Associated attendee registration', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='registrations.registration')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['scheduled_at', 'created_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='idx_notif_status_sched'), models.Index(fields=['status', 'processing_started_at'], name='idx_notif_status_proc')],
            },
        ),
    ]
