# Generated by Django 5.1.15 on 2026-09-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.SlugField(default='public-speaking-workshop', help_text='Unique identifier for the workshop', primary_key=True, serialize=False)),
                ('title', models.CharField(default='Public Speaking Workshop', help_text='Exact title of the workshop', max_length=200)),
                ('scheduled_at', models.DateTimeField(db_index=True, help_text='Scheduled date and time in Asia/Kolkata timezone (18 Sept 2026, 3:30 PM IST)')),
                ('timezone', models.CharField(default='Asia/Kolkata', help_text='IANA Timezone name', max_length=50)),
                ('reminder_lead_minutes', models.PositiveIntegerField(default=15, help_text='Minutes before workshop to trigger reminder (e.g. 15 minutes)')),
                ('meeting_link', models.URLField(blank=True, help_text='Optional meeting link for the session', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether registrations are actively accepted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workshop',
                'verbose_name_plural': 'Workshops',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
