# Generated by Django 5.1.15 on 2026-09-17 14:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique registration identifier', primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='Full name of the attendee', max_length=150)),
                ('email', models.EmailField(help_text='Raw email address as provided by attendee', max_length=254)),
                ('normalized_email', models.EmailField(db_index=True, help_text='Trimmed and lowercased email for deduplication', max_length=254)),
                ('phone_number', models.CharField(db_index=True, help_text='Normalized E.164 formatted phone number (e.g. +919876543210)', max_length=20)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Unique key ensuring idempotent API submission', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workshop', models.ForeignKey(help_text='The workshop this registration is for', on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='workshops.workshop')),
            ],
            options={
                'verbose_name': 'Registration',
                'verbose_name_plural': 'Registrations',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('workshop', 'normalized_email'), name='unique_workshop_normalized_email')],
            },
        ),
    ]
