# Generated by Django 5.1.15 on 2026-09-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='request_fingerprint',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 fingerprint of request parameters for idempotency conflict detection', max_length=64, null=True),
        ),
    ]
