# Generated by Django 5.1.15 on 2026-09-17 15:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_registration_request_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Original idempotency key from initial registration submission', max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique idempotency record identifier', primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, help_text='Unique idempotency key identifying an API operation', max_length=64, unique=True)),
                ('request_fingerprint', models.CharField(db_index=True, help_text='SHA-256 fingerprint of request parameters for conflict detection', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(help_text='The registration associated with this idempotency key', on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to='registrations.registration')),
            ],
            options={
                'verbose_name': 'Idempotency Record',
                'verbose_name_plural': 'Idempotency Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
