# Generated by Django 5.1.15 on 2026-09-17 14:34

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique event identifier for transactional outbox pattern', primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, help_text='Event name (e.g. registration.created, workshop.reminder)', max_length=50)),
                ('aggregate_type', models.CharField(help_text='Aggregate model name (e.g. Registration, Notification)', max_length=50)),
                ('aggregate_id', models.UUIDField(db_index=True, help_text='ID of the aggregate this event pertains to')),
                ('payload', models.JSONField(default=dict, help_text='JSON payload to dispatch to the automation webhook')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Current delivery state', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when worker leased/claimed this event for processing', null=True)),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of retry attempts executed')),
                ('max_retries', models.PositiveIntegerField(default=5, help_text='Maximum allowed dispatch attempts before permanent failure')),
                ('next_retry_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Next scheduled attempt timestamp with exponential backoff')),
                ('last_error', models.TextField(blank=True, help_text='Error message from the last failed dispatch attempt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='Timestamp when automation webhook acknowledged receipt (HTTP 2xx)', null=True)),
            ],
            options={
                'verbose_name': 'Outbox Event',
                'verbose_name_plural': 'Outbox Events',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='idx_outbox_status_retry'), models.Index(fields=['status', 'processing_started_at'], name='idx_outbox_status_proc')],
            },
        ),
    ]
