# Generated by Django 5.1.15 on 2026-09-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='outboxevent',
            constraint=models.UniqueConstraint(fields=('aggregate_id', 'event_type'), name='unique_outbox_aggregate_event_type'),
        ),
    ]
